name: lint

on:
  push:
    paths:
      - 'streamable/**'
      - 'tests/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: checks
      run: make venv lint
