name: test

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: unittest
      run: |
        python -m pip install -r requirements.txt
        python -m unittest

  typing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: unittest
      run: |
        python -m pip install -r requirements.txt
        python -m mypy kioss tests

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: unittest
      run: |
        python -m pip install -r requirements.txt
        python -m black --check kioss/* tests/*
